dsi_panel: fix indention
../../../../../../kernel/motorola/sm6375/techpack/display/msm/dsi/dsi_panel.c:1326:3: error: misleading indentation; sta
tement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
 1326 |                 rc = dsi_panel_send_param_cmd(panel, param_info);
      |                 ^
../../../../../../kernel/motorola/sm6375/techpack/display/msm/dsi/dsi_panel.c:1323:2: note: previous statement is here
 1323 |         if (panel->lhbm_config.lhbm_wait_for_fps_valid && param_info->value == HBM_FOD_ON_STATE)
      |         ^

Broken code was added by Motorola:
https://github.com/MotorolaMobilityLLC/kernel-msm-5.4-techpack-display/commit/d67e46e138eb9e61359cd90b92786417152d8dea

Change-Id: If122cbae26b5e8a23f9766cf685d3a3599adc8f5
Signed-off-by: Sevenrock <sevenrock@hotmail.de>