Revert "disp: msm: dsi: Add print info for DSI_CTRL"
This reverts commit 3a743de84d19295179568ab2f75f6018fd003445.

Fixes build error

../../../../../../kernel/motorola/sm6375/techpack/display/msm/dsi/dsi_display.c:8542:27: error: unused variable 'ctrl' [
-Werror,-Wunused-variable]
 8542 |         struct dsi_display_ctrl *ctrl = &display->ctrl[0];

by reverting Motorola commit
https://github.com/MotorolaMobilityLLC/kernel-msm-5.4-techpack-display/commit/942f7d4bcfd2f8fcbb7446df482f4efdfb0b469c
which also reduces log spam.

Change-Id: I3a394ecf8c452eecd367236e0b01f48e5b2d1b0a
Signed-off-by: Sevenrock <sevenrock@hotmail.de>