Make compatible for fallthrough
On some lower version GCC compiler,fallthrough does not define and will
cause compile error:
error: use of undeclared identifier 'fallthrough'

Change-Id: Ie86ca8703d84a6d06faddc159380a7f4ed40a6a7
Signed-off-by: Wenge Zhu <zhuwg1@motorola.com>
Reviewed-on: https://gerrit.mot.com/2775802
Reviewed-by: Wei Deng <dengwei1@motorola.com>
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Jichao Zou <zoujc@motorola.com>
Submit-Approved: Jira Key