Fix goodix touch driver build error
Fix goodix touch driver build error due to
compiler optimization level:
goodix_ts_log_capture.c:36:6: error: variable 'ret' set but not used

Change-Id: Iaec12d4ee42285ce04ca5a3685399855752ed36a
Signed-off-by: Wenge Zhu <zhuwg1@motorola.com>
Reviewed-on: https://gerrit.mot.com/2739578
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Jichao Zou <zoujc@motorola.com>
Submit-Approved: Jira Key